# Generated by Django 2.1 on 2018-08-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AddField(
            model_name='interview',
            name='avatar',
            field=models.ImageField(default='fakeavatar.jpg', upload_to='avatars', verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.CharField(blank=True, max_length=32, verbose_name='服务处所'),
        ),
        migrations.AddField(
            model_name='interview',
            name='education',
            field=models.CharField(blank=True, max_length=32, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='头衔'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮件地址'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='FakeSlug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
