# Generated by Django 2.1 on 2018-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20180816_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.CharField(blank=True, max_length=32, verbose_name='厂商'),
        ),
    ]
